// Placeholder for future DAC / serial streaming utilities.
# Example API:
# class DACStreamer:
#     def __init__(self, device='COM3'): ...
#     def start(self): ...
#     def write_samples(self, samples): ...
#     def stop(self): ...
